E-Apteka/Models/Medicine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_Apteka.Models
{
    public class Medicine
    {
        [Key]
        public int Id { get; set; }
        public string Producer { get; set; }
        public double Price { get; set; }
        public string Name { get; set; }

    }
}

E-Apteka/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using E_Apteka.Models;
namespace E_Apteka.Controllers
{
    [Authorize(Roles ="User")]
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Buy(int id)
        {
            ProductModel productModel = new ProductModel();
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { medicine = productModel.find(id), Quantity = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { medicine = productModel.find(id), Quantity = 1 });
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].medicine.Id.Equals(id))
                    return i;
            return -1;
        }
    }
}

E-Apteka/Controllers/MedicinesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Apteka.Models;

namespace E_Apteka.Controllers
{
    [Authorize]
    public class MedicinesController : Controller
    {
        private MedicineContext db = new MedicineContext();
        public List<Medicine> lekovi = new List<Medicine>();
        // GET: Medicines
        public ActionResult Index()
        {
            return View(db.Medicines.ToList());
        }

        // GET: Medicines/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // GET: Medicines/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medicines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Producer,Price,Name")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Medicines.Add(medicine);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicine);
        }

        // GET: Medicines/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Producer,Price,Name")] Medicine medicine)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicine).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicine);
        }

        // GET: Medicines/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicine medicine = db.Medicines.Find(id);
            if (medicine == null)
            {
                return HttpNotFound();
            }
            return View(medicine);
        }

        // POST: Medicines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicine medicine = db.Medicines.Find(id);
            db.Medicines.Remove(medicine);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        [Authorize(Roles ="User")]
        public ActionResult Naracaj()
        {
            Pharmacy model = new Pharmacy();
            return View(model);
            
        }

        [HttpPost]
        public ActionResult Naracaj(Pharmacy p)
        {
            
            List<Item> cart = (List<Item>)Session["cart"];
            Random r = new Random();
            int idOrder = r.Next();
            foreach (var item in cart)
            {
                OrderItem model = new OrderItem() { Medicine = item.medicine.Name, Pharmacy = p.selectedPharmacy, OrderId = idOrder };
                db.Orders.Add(model);
                db.SaveChanges();
            }

            Session["cart"] = null;
            return RedirectToAction("ZavrsiNaracka");
        }
        [Authorize(Roles = "User")]
        public ActionResult ZavrsiNaracka()
        {
            return View();
        }

        [Authorize(Roles ="Administrator")]
        public ActionResult ListOrders()
        {
            List<OrderItem> listOrders = db.Orders.ToList();
            List<Order> orders = new List<Order>();
            List<int> orderIds = new List<int>();
            foreach (var item in listOrders)
            {
                if (!orderIds.Contains(item.OrderId))
                {
                    orderIds.Add(item.OrderId);
                    orders.Add(new Order() { orderId = item.OrderId, pharmacy = item.Pharmacy });
                }
            }
            foreach (var item in listOrders)
            {
                orders.Find(m => m.orderId == item.OrderId).medicines.Add(item.Medicine);
            }

            return View(orders);
        }


    }
}

E-Apteka/Views/Medicines/AddToShoppingCart.cshtml
@model E_Apteka.Models.Medicine

@{
    ViewBag.Title = "AddToShoppingCart";
}

<h2>AddToShoppingCart</h2>

E-Apteka/Views/Medicines/Create.cshtml
@model E_Apteka.Models.Medicine

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E-Apteka/Views/Medicines/Delete.cshtml
@model E_Apteka.Models.Medicine

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

E-Apteka/Views/Medicines/Details.cshtml
@model E_Apteka.Models.Medicine

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Medicine</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Producer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Producer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

E-Apteka/Views/Medicines/Edit.cshtml
@model E_Apteka.Models.Medicine

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Medicine</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Producer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Producer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Producer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E-Apteka/Views/Medicines/Index.cshtml
@model IEnumerable<E_Apteka.Models.Medicine>

@{
    ViewBag.Title = "Index";
}

@if (User.IsInRole("Administrator"))
{
    <br />
    @Html.ActionLink("Листа на нарачки", "ListOrders", "Medicines", new { @class = "btn btn-primary " })
}
<h2>Листа на лекови</h2>

<div>

</div>
<table class="table" id="medicineTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @if (User.IsInRole("User"))
                    {
                        <a class="btn btn-default" href="@Url.Action("Buy","Cart",new { id=item.Id})">Додади во кошничка</a>
                    }
                </td>
            </tr>
        }
    </tbody>

</table>
@section scripts{
    <script>
        $("#medicineTable").DataTable();

    </script>
}

E-Apteka/Views/Medicines/ListOrders.cshtml
@using E_Apteka.Models
@model IEnumerable<Order>
@{
    ViewBag.Title = "ListOrders";
}

<h2>Листа на нарачки</h2>
<br />

@*@Html.BeginForm("ListOrders", "Medicines") {*@
    @foreach(var item in Model)
    {
        <div>
            <p>Нарачка бр. @item.orderId</p>
            <p>Аптека за која е направена нарачката: @item.pharmacy</p>
            <p>Листа на лекови кои се нарачани: </p>
            @foreach(var medicine in item.medicines)
            {
                <p>@medicine.ToString()</p>
            }
        </div>
        <hr />
    }
@*}*@

E-Apteka/Views/Medicines/Naracaj.cshtml
@model E_Apteka.Models.Pharmacy

@{
    ViewBag.Title = "Нарачај";
}

<h2>Одберете аптека<h2>

@using (Html.BeginForm("Naracaj", "Medicines"))
{
<div class="form-group">
    @Html.DropDownListFor(m => m.selectedPharmacy, new SelectList(Model.pharmacies), new { @class = "form-control" })
</div>
    E_Apteka.Models.OrderItem o = new E_Apteka.Models.OrderItem();
    @Html.Hidden(o.Id.ToString());
    <button type="submit" class="btn btn-success">Нарачај</button>
}

    

E-Apteka/Views/Medicines/ZavrsiNaracka.cshtml
@using E_Apteka.Models;
@{
    ViewBag.Title = "ZavrsiNaracka";
}

<h2>Вашата нарачка е примена.</h2>
<br />

<a href="/Medicines/Index" class="btn btn-success">Вратете се на почетната страница</a>